# Generated by Django 5.1.4 on 2025-04-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
